### PR TITLE
kommander revision 51: removed image selection of catalog and pointing to version 0.8.36

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What type of PR is this?**
Chore

Bug

**What this PR does/ why we need it**:

This PR removes the explicit choice of image version for Catalog, which should only be done through an override of values not explicitly here. 

**Which issue(s) this PR fixes**:

https://jira.d2iq.com/browse/D2IQ-69905

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] The commit message explains the changes and why are needed.
- [ ] The code builds and passes lint/style checks locally.
- [ ] The relevant subset of integration tests pass locally.
- [ ] The core changes are covered by tests.
- [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by alejandroEsc** [comment]
blocked on: https://github.com/mesosphere/kubeaddons-kommander/pull/112 will wait for this to merge first.

**Comment by juliangieseke** [comment]
^ that or add a JIRA which refers to the changes made 👍

**Comment by alejandroEsc** [comment]
> ^ that or add a JIRA which refers to the changes made 👍

I updated, sorry I thought i did fill that in, but i had to rebase and make changes, so I guess i forgot to do that. First time I do this, a simple reminder would help, @makkes please review again.

**Comment by alejandroEsc** [comment]
closing in favor of https://github.com/mesosphere/kubeaddons-kommander/pull/115

**Pull request closed without merging**
