### PR TITLE
Add e2e tests

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
**What type of PR is this?**

Testing

**What this PR does/ why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] The commit message explains the changes and why are needed.
- [ ] The code builds and passes lint/style checks locally.
- [ ] The relevant subset of integration tests pass locally.
- [ ] The core changes are covered by tests.
- [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
@shaneutt Do you have a hint on how I can debug that the kommander addon is not being deployed successfully?

**Comment by juliangieseke** [comment]
not sure if this PR is still active, but it has conflicts.

**Comment by DanielMSchmidt** [comment]
@juliangieseke will rebase once the E2E tests pass in the ui repo again

**Comment by DanielMSchmidt** [comment]
@shaneutt Any idea why the kommander addon does not start? Am I missing configuration [here](https://github.com/mesosphere/kubeaddons-kommander/pull/164/commits/2b9c90420dbc664de39d9daddee99ab54ff83912#diff-39b3ad7311c3042f9da1bc21c9245fbdR90)

**Comment by shaneutt** [comment]
> @shaneutt Any idea why the kommander addon does not start? Am I missing configuration [here](https://github.com/mesosphere/kubeaddons-kommander/pull/164/commits/2b9c90420dbc664de39d9daddee99ab54ff83912#diff-39b3ad7311c3042f9da1bc21c9245fbdR90)

I will try to follow up on this soon.

**Comment by joejulian** [comment]
I bumped the kubeaddons test library to try to get some more details in the output.

**Comment by makkes** [comment]
```[02:21:51] # github.com/mesosphere/kubeaddons-kommander-addons/test [github.com/mesosphere/kubeaddons-kommander-addons/test.test]
[02:21:51] ./kommander_test.go:71:74: not enough arguments in call to utils.GetLatestAddonRevisionFromLocalRepoBranch
[02:21:51] 	have (string, string, string)
[02:21:51] 	want (string, string, string, string)
[02:21:51] note: module requires Go 1.15```

**Review by makkes — COMMENTED** [review]
@DanielMSchmidt would you mind adding some documentation to this repo on how to run the tests locally and maybe a short explanation of what they do (spin up cluster, fetch tests from here and there, run them, put output somewhere, etc.)?

**Comment by DanielMSchmidt** [comment]
@makkes Any idea why the e2e tests fails when creating a cluster?


```
fluentbit                                                              [OK]
elasticsearchexporter                                                  [OK]
kibana                                                                 [OK]

Error: failed to deploy the cluster: the following 1 addons failed to deploy: [ kommander ]
kommander                                                              [ERROR]
time="2020-10-02T14:42:10.997933556Z" level=info msg="shim reaped" id=64d77effaaddd0d58edfd6c6d62ac2715029a77187dfd21a2dfddce65b7f1073 
time="2020-10-02T14:42:11.008771173Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
exit status 1
+ teardown
```

**Review by makkes — APPROVED** [review]

**Pull request closed without merging**
