### PR TITLE
chore: bump kcl version

### PR DESCRIPTION
**Pull request by hectorj2f**

### CODE REVIEW

**Comment by makkes** [comment]
Oh shit, I just merged a wip PR. Was it supposed to be WIP, @hectorj2f?

**Comment by hectorj2f** [comment]
Yes, It was WIP. It won't break anything but I will have to open a new PR to add more changes

**Comment by makkes** [comment]
> Yes, It was WIP. It won't break anything but I will have to open a new PR to add more changes
> 

I'm so sorry

**Comment by juliangieseke** [comment]
@hectorj2f given tomorrow is soak update / beta2 codefreeze, do you _need_ to get another one in before that happens?

**Comment by hectorj2f** [comment]
@juliangieseke we need another bump, tomorrow is the release day for Konvoy and others

**Comment by hectorj2f** [comment]
Please, take into account that we had experienced many issues with AWS on CI

**Comment by juliangieseke** [comment]
ok. kommander beta 1 release was today (i just did it), tomorrow is _code freeze_ for beta 2, which will be released on may 13. lets try to get it in by EU EOD tomorrow, otherwise we can sync how to proceed (revert this PR for the time being or update soak with updated KCL as soon as it lands)

**Comment by samvantran** [comment]
> will be released on may 13

@juliangieseke you mean May 6? 🙏

**Pull request merged**
