### PR TITLE
chore: remove values from addon (added to chart)

### PR DESCRIPTION
**Pull request by juliangieseke**
companion PR for: https://github.com/mesosphere/charts/pull/512

### CODE REVIEW

**Comment by hectorj2f** [comment]
Let's note that this will cause an pod restart due to the changes in the chart settings for this addon.

**Comment by juliangieseke** [comment]
I guess updating from 1.0.0 to 1.1.0 will cause a restart anyway, am I correct? 🤔 So it should be a non issue

**Comment by hectorj2f** [comment]
yes, it'll update it if the deployment or any other Kubernetes resource templates had any changes... otherwise it won't.

**Comment by juliangieseke** [comment]
closing this after talking about in sync.

**Pull request closed without merging**
