### PR TITLE
[1.0.x] Kommander 1.0.1 bits n pieces 

### PR DESCRIPTION
**Pull request by juliangieseke**
- [x] adds 1.16.8 to selectable k8s versions https://jira.d2iq.com/browse/D2IQ-67811
- [x] increases appversion to 1.0.1 
- [x] kcl image bump https://jira.d2iq.com/browse/D2IQ-67475

### CODE REVIEW

**Comment by hectorj2f** [comment]
can we get the KCL version bump as part of this PR ? or do we prefer to do it as part of a different PR ?

**Comment by juliangieseke** [comment]
this PR is fine 👍

**Comment by msdolbey** [comment]
Related to this JIRA: 
[D2IQ-67475](https://jira.d2iq.com/browse/D2IQ-67475)

**Comment by juliangieseke** [comment]
also related to https://jira.d2iq.com/browse/D2IQ-67811

**Comment by shaneutt** [comment]
@juliangieseke this is marked as `wip` but it looks `ready` is it `ready`?

**Pull request merged**
