### PR TITLE
Kommander chart bump

### PR DESCRIPTION
**Pull request by natmegs**
Depends on mesosphere/charts#686 

**What type of PR is this?**

Chore

**What this PR does/ why we need it**:

Bump kommander chart

**Which issue(s) this PR fixes**:
Remove catalog override: https://jira.d2iq.com/browse/D2IQ-69905
UI bump: 
```
jql=labels in ( ksphere-ui:v3.126.1, ksphere-ui:v3.126.0, ksphere-ui:v3.125.4, ksphere-ui:v3.125.3, ksphere-ui:v3.125.2, ksphere-ui:v3.125.1, ksphere-ui:v3.125.0, ksphere-ui:v3.124.2, ksphere-ui:v3.124.1, ksphere-ui:v3.124.0, ksphere-ui:v3.123.0, ksphere-ui:v3.122.5, ksphere-ui:v3.122.4, ksphere-ui:v3.122.3)
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

**Checklist**

- [ ] The commit message explains the changes and why are needed.
- [ ] The code builds and passes lint/style checks locally.
- [ ] The relevant subset of integration tests pass locally.
- [ ] The core changes are covered by tests.
- [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by natmegs** [comment]
Blocked until charts PR merges

**Comment by alejandroEsc** [comment]
Could you please wait on https://github.com/mesosphere/kubeaddons-kommander/pull/113 and then take on those changes?

**Comment by alejandroEsc** [comment]
I am also ok closing my PR in favor of this one as long as you do the same changes, nothing complicated.

**Comment by natmegs** [comment]
@alejandroEsc I added a commit to remove the image items from kubeaddons-catalog - let me know if there's anything else from that PR that I missed

**Comment by alejandroEsc** [comment]
> @alejandroEsc I added a commit to remove the image items from kubeaddons-catalog - let me know if there's anything else from that PR that I missed

thank you!!!

**Pull request merged**
