### PR TITLE
Automated chart bump kommander-0.13.2

### PR DESCRIPTION
**Pull request by d2iq-dispatch**
**What type of PR is this?**

Bug

**What this PR does/ why we need it**:

new config block was added to the wrong location and caused the below grafana block to be put in the wrong location (bug intro'd in previous version https://github.com/mesosphere/charts/pull/904/files#diff-27ff036ff511571cd28603ccf34d46b315397788280fb0b35d6aaae9c451080eR253). this ended up with another grafana instance installation attempt which caused issues

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

* [x] *If a chart is changed, the chart version is correctly incremented.*
* [x] The commit message explains the changes and why are needed.
* [ ] The code builds and passes lint/style checks locally.
* [ ] The relevant subset of integration tests pass locally.
* [ ] The core changes are covered by tests.
* [ ] The documentation is updated where needed.

### CODE REVIEW

**Comment by gracedo** [comment]
I successfully brought up a kommander cluster using this config, but tests are still failing to deploy kommander... 🤔

**Comment by juliangieseke** [comment]
> Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading

tried rerunning, not 100% sure thats the correct thing to do tho 🙈

**Comment by juliangieseke** [comment]
> addons.go:114: waiting for addons: map[kommander:0xc0025d7800]
> 16:35:34
>  panic: test timed out after 40m0s

**Comment by gracedo** [comment]
closing in favor of https://github.com/mesosphere/kubeaddons-kommander/pull/236

**Pull request closed without merging**
